/*
 * My Data My Consent - Developer API
 * Unleashing the power of consent by establishing trust. The Platform Core Developer API defines a set of capabilities that can be used to request, issue, manage and update data, documents and credentials by organizations. The API can be used to request, manage and update Decentralised Identifiers, Financial Data, Health Data issue Documents, Credentials directly or using OpenID Connect flows, and verify Messages signed with DIDs and much more.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@mydatamyconsent.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mydatamyconsent.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.mydatamyconsent.model.ConsentedFinancialAccount;
import com.mydatamyconsent.model.ConsentedFinancialAccountFieldTransactionPeriod;
import com.mydatamyconsent.model.FinancialAccountDetailsRequired;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ConsentedFinancialAccountField
 */
public class ConsentedFinancialAccountFieldTest {
    private final ConsentedFinancialAccountField model = new ConsentedFinancialAccountField();

    /**
     * Model tests for ConsentedFinancialAccountField
     */
    @Test
    public void testConsentedFinancialAccountField() {
        // TODO: test ConsentedFinancialAccountField
    }

    /**
     * Test the property 'fieldTitle'
     */
    @Test
    public void fieldTitleTest() {
        // TODO: test fieldTitle
    }

    /**
     * Test the property 'fieldSlug'
     */
    @Test
    public void fieldSlugTest() {
        // TODO: test fieldSlug
    }

    /**
     * Test the property 'requestedDetails'
     */
    @Test
    public void requestedDetailsTest() {
        // TODO: test requestedDetails
    }

    /**
     * Test the property 'transactionPeriod'
     */
    @Test
    public void transactionPeriodTest() {
        // TODO: test transactionPeriod
    }

    /**
     * Test the property 'consentedAccounts'
     */
    @Test
    public void consentedAccountsTest() {
        // TODO: test consentedAccounts
    }

}
