/*
 * My Data My Consent - Developer API
 * Unleashing the power of consent by establishing trust. The Platform Core Developer API defines a set of capabilities that can be used to request, issue, manage and update data, documents and credentials by organizations. The API can be used to request, manage and update Decentralised Identifiers, Financial Data, Health Data issue Documents, Credentials directly or using OpenID Connect flows, and verify Messages signed with DIDs and much more.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@mydatamyconsent.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mydatamyconsent.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.mydatamyconsent.model.DataProtectionOfficer;
import com.mydatamyconsent.model.SupportedDocumentType;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for DataProviderDetails
 */
public class DataProviderDetailsTest {
    private final DataProviderDetails model = new DataProviderDetails();

    /**
     * Model tests for DataProviderDetails
     */
    @Test
    public void testDataProviderDetails() {
        // TODO: test DataProviderDetails
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'category'
     */
    @Test
    public void categoryTest() {
        // TODO: test category
    }

    /**
     * Test the property 'logoUrl'
     */
    @Test
    public void logoUrlTest() {
        // TODO: test logoUrl
    }

    /**
     * Test the property 'website'
     */
    @Test
    public void websiteTest() {
        // TODO: test website
    }

    /**
     * Test the property 'supportEmail'
     */
    @Test
    public void supportEmailTest() {
        // TODO: test supportEmail
    }

    /**
     * Test the property 'helpLineNumber'
     */
    @Test
    public void helpLineNumberTest() {
        // TODO: test helpLineNumber
    }

    /**
     * Test the property 'privacyPolicy'
     */
    @Test
    public void privacyPolicyTest() {
        // TODO: test privacyPolicy
    }

    /**
     * Test the property 'termOfService'
     */
    @Test
    public void termOfServiceTest() {
        // TODO: test termOfService
    }

    /**
     * Test the property 'dataProtectionOfficer'
     */
    @Test
    public void dataProtectionOfficerTest() {
        // TODO: test dataProtectionOfficer
    }

    /**
     * Test the property 'supportedDocumentTypes'
     */
    @Test
    public void supportedDocumentTypesTest() {
        // TODO: test supportedDocumentTypes
    }

    /**
     * Test the property 'supportedAccountTypes'
     */
    @Test
    public void supportedAccountTypesTest() {
        // TODO: test supportedAccountTypes
    }

}
