/*
 * My Data My Consent - Developer API
 * Unleashing the power of data consent by establishing trust. The Platform Core Developer API defines a set of capabilities that can be used to request, issue, manage and update data, documents and credentials by organizations. The API can be used to request, manage and update Decentralised Identifiers, Financial Data, Health Data issue Documents, Credentials directly or using OpenID Connect flows, and verify Messages signed with DIDs and much more.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@mydatamyconsent.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mydatamyconsent.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.UUID;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for DataConsentRequestedFinancialAccount
 */
public class DataConsentRequestedFinancialAccountTest {
    private final DataConsentRequestedFinancialAccount model = new DataConsentRequestedFinancialAccount();

    /**
     * Model tests for DataConsentRequestedFinancialAccount
     */
    @Test
    public void testDataConsentRequestedFinancialAccount() {
        // TODO: test DataConsentRequestedFinancialAccount
    }

    /**
     * Test the property 'customKey'
     */
    @Test
    public void customKeyTest() {
        // TODO: test customKey
    }

    /**
     * Test the property 'drn'
     */
    @Test
    public void drnTest() {
        // TODO: test drn
    }

    /**
     * Test the property 'accountTypeId'
     */
    @Test
    public void accountTypeIdTest() {
        // TODO: test accountTypeId
    }

    /**
     * Test the property 'accountIdentifier'
     */
    @Test
    public void accountIdentifierTest() {
        // TODO: test accountIdentifier
    }

}
