/*
 * My Data My Consent - Developer API
 * Unleashing the power of data consent by establishing trust. The Platform Core Developer API defines a set of capabilities that can be used to request, issue, manage and update data, documents and credentials by organizations. The API can be used to request, manage and update Decentralised Identifiers, Financial Data, Health Data issue Documents, Credentials directly or using OpenID Connect flows, and verify Messages signed with DIDs and much more.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@mydatamyconsent.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mydatamyconsent.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.mydatamyconsent.model.SuggestedAccountDto;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for DataConsentRequestedAccountDto
 */
public class DataConsentRequestedAccountDtoTest {
    private final DataConsentRequestedAccountDto model = new DataConsentRequestedAccountDto();

    /**
     * Model tests for DataConsentRequestedAccountDto
     */
    @Test
    public void testDataConsentRequestedAccountDto() {
        // TODO: test DataConsentRequestedAccountDto
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'accountTypeId'
     */
    @Test
    public void accountTypeIdTest() {
        // TODO: test accountTypeId
    }

    /**
     * Test the property 'suggestedAccounts'
     */
    @Test
    public void suggestedAccountsTest() {
        // TODO: test suggestedAccounts
    }

    /**
     * Test the property 'issuer'
     */
    @Test
    public void issuerTest() {
        // TODO: test issuer
    }

    /**
     * Test the property 'issuerLogoUrls'
     */
    @Test
    public void issuerLogoUrlsTest() {
        // TODO: test issuerLogoUrls
    }

    /**
     * Test the property 'requestedDataType'
     */
    @Test
    public void requestedDataTypeTest() {
        // TODO: test requestedDataType
    }

    /**
     * Test the property 'optional'
     */
    @Test
    public void optionalTest() {
        // TODO: test optional
    }

}
