/*
 * My Data My Consent - Developer API
 * Unleashing the power of data consent by establishing trust. The Platform Core Developer API defines a set of capabilities that can be used to request, issue, manage and update data, documents and credentials by organizations. The API can be used to request, manage and update Decentralised Identifiers, Financial Data, Health Data issue Documents, Credentials directly or using OpenID Connect flows, and verify Messages signed with DIDs and much more.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@mydatamyconsent.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mydatamyconsent.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.mydatamyconsent.model.DocumentIssueRequestStatus;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.UUID;
import org.openapitools.jackson.nullable.JsonNullable;
import org.threeten.bp.OffsetDateTime;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for DocumentIssueRequestDetails
 */
public class DocumentIssueRequestDetailsTest {
    private final DocumentIssueRequestDetails model = new DocumentIssueRequestDetails();

    /**
     * Model tests for DocumentIssueRequestDetails
     */
    @Test
    public void testDocumentIssueRequestDetails() {
        // TODO: test DocumentIssueRequestDetails
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'documentTypeId'
     */
    @Test
    public void documentTypeIdTest() {
        // TODO: test documentTypeId
    }

    /**
     * Test the property 'typeName'
     */
    @Test
    public void typeNameTest() {
        // TODO: test typeName
    }

    /**
     * Test the property 'identifier'
     */
    @Test
    public void identifierTest() {
        // TODO: test identifier
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'receiver'
     */
    @Test
    public void receiverTest() {
        // TODO: test receiver
    }

    /**
     * Test the property 'issuedAtUtc'
     */
    @Test
    public void issuedAtUtcTest() {
        // TODO: test issuedAtUtc
    }

    /**
     * Test the property 'validFromUtc'
     */
    @Test
    public void validFromUtcTest() {
        // TODO: test validFromUtc
    }

    /**
     * Test the property 'expiresAtUtc'
     */
    @Test
    public void expiresAtUtcTest() {
        // TODO: test expiresAtUtc
    }

    /**
     * Test the property 'metaData'
     */
    @Test
    public void metaDataTest() {
        // TODO: test metaData
    }

    /**
     * Test the property 'createdAtUtc'
     */
    @Test
    public void createdAtUtcTest() {
        // TODO: test createdAtUtc
    }

}
