/*
 * My Data My Consent - Developer API
 * Unleashing the power of data consent by establishing trust. The Platform Core Developer API defines a set of capabilities that can be used to request, issue, manage and update data, documents and credentials by organizations. The API can be used to request, manage and update Decentralised Identifiers, Financial Data, Health Data issue Documents, Credentials directly or using OpenID Connect flows, and verify Messages signed with DIDs and much more.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@mydatamyconsent.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mydatamyconsent.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.mydatamyconsent.model.DataConsentStatus;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.UUID;
import org.openapitools.jackson.nullable.JsonNullable;
import org.threeten.bp.OffsetDateTime;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for OrganizationDataConsentInfoDto
 */
public class OrganizationDataConsentInfoDtoTest {
    private final OrganizationDataConsentInfoDto model = new OrganizationDataConsentInfoDto();

    /**
     * Model tests for OrganizationDataConsentInfoDto
     */
    @Test
    public void testOrganizationDataConsentInfoDto() {
        // TODO: test OrganizationDataConsentInfoDto
    }

    /**
     * Test the property 'consentRequestId'
     */
    @Test
    public void consentRequestIdTest() {
        // TODO: test consentRequestId
    }

    /**
     * Test the property 'userId'
     */
    @Test
    public void userIdTest() {
        // TODO: test userId
    }

    /**
     * Test the property 'consentTemplateId'
     */
    @Test
    public void consentTemplateIdTest() {
        // TODO: test consentTemplateId
    }

    /**
     * Test the property 'consentPurpose'
     */
    @Test
    public void consentPurposeTest() {
        // TODO: test consentPurpose
    }

    /**
     * Test the property 'consentDescription'
     */
    @Test
    public void consentDescriptionTest() {
        // TODO: test consentDescription
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'createdAtUtc'
     */
    @Test
    public void createdAtUtcTest() {
        // TODO: test createdAtUtc
    }

    /**
     * Test the property 'organizationId'
     */
    @Test
    public void organizationIdTest() {
        // TODO: test organizationId
    }

    /**
     * Test the property 'consentSentToOrganization'
     */
    @Test
    public void consentSentToOrganizationTest() {
        // TODO: test consentSentToOrganization
    }

}
