/*
 * My Data My Consent - Developer API
 * Unleashing the power of data consent by establishing trust. The Platform Core Developer API defines a set of capabilities that can be used to request, issue, manage and update data, documents and credentials by organizations. The API can be used to request, manage and update Decentralised Identifiers, Financial Data, Health Data issue Documents, Credentials directly or using OpenID Connect flows, and verify Messages signed with DIDs and much more.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@mydatamyconsent.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mydatamyconsent.api;

import com.mydatamyconsent.ApiException;
import com.mydatamyconsent.model.DataProvider;
import com.mydatamyconsent.model.DataProviderPaginatedList;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DataProviderDiscoveryApi
 */
@Ignore
public class DataProviderDiscoveryApiTest {

    private final DataProviderDiscoveryApi api = new DataProviderDiscoveryApi();

    
    /**
     * Discover all data providers in My Data My Consent by country and filters.
     *
     * .
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void v1DataProvidersGetTest() throws ApiException {
        String accountType = null;
        String documentType = null;
        String organizationCategory = null;
        Integer pageNo = null;
        Integer pageSize = null;
        String country = null;
        DataProviderPaginatedList response = api.v1DataProvidersGet(accountType, documentType, organizationCategory, pageNo, pageSize, country);

        // TODO: test validations
    }
    
    /**
     * Get a Data Provider details.
     *
     * .
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void v1DataProvidersProviderIdGetTest() throws ApiException {
        String providerId = null;
        DataProvider response = api.v1DataProvidersProviderIdGet(providerId);

        // TODO: test validations
    }
    
}
